"""create product

Revision ID: 7536a64b6931
Revises: ee13079f6e79
Create Date: 2024-07-28 17:51:29.854484

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '7536a64b6931'
down_revision: Union[str, None] = 'ee13079f6e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
